// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package linear

import (
	"context"
	"encoding/json"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// CommentByIDComment includes the requested fields of the GraphQL type Comment.
// The GraphQL type's documentation follows.
//
// A comment associated with an issue, project update, initiative update, document content, post, project, or initiative. Comments support rich text (ProseMirror), emoji reactions, and threaded replies via parentId. Comments can be created by workspace users or by external users through integrations (e.g., Slack, Intercom). Each comment belongs to exactly one parent entity.
type CommentByIDComment struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The comment content in markdown format. This is a derived representation of the canonical bodyData ProseMirror content.
	Body string `json:"body"`
	// The issue that the comment is associated with. Null if the comment belongs to a different parent entity type.
	Issue *CommentByIDCommentIssue `json:"issue"`
}

// GetId returns CommentByIDComment.Id, and is useful for accessing the field via an interface.
func (v *CommentByIDComment) GetId() string { return v.Id }

// GetBody returns CommentByIDComment.Body, and is useful for accessing the field via an interface.
func (v *CommentByIDComment) GetBody() string { return v.Body }

// GetIssue returns CommentByIDComment.Issue, and is useful for accessing the field via an interface.
func (v *CommentByIDComment) GetIssue() *CommentByIDCommentIssue { return v.Issue }

// CommentByIDCommentIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type CommentByIDCommentIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
}

// GetIdentifier returns CommentByIDCommentIssue.Identifier, and is useful for accessing the field via an interface.
func (v *CommentByIDCommentIssue) GetIdentifier() string { return v.Identifier }

// CommentByIDResponse is returned by CommentByID on success.
type CommentByIDResponse struct {
	// A specific comment.
	Comment CommentByIDComment `json:"comment"`
}

// GetComment returns CommentByIDResponse.Comment, and is useful for accessing the field via an interface.
func (v *CommentByIDResponse) GetComment() CommentByIDComment { return v.Comment }

// CommentFields includes the GraphQL fields of Comment requested by the fragment CommentFields.
// The GraphQL type's documentation follows.
//
// A comment associated with an issue, project update, initiative update, document content, post, project, or initiative. Comments support rich text (ProseMirror), emoji reactions, and threaded replies via parentId. Comments can be created by workspace users or by external users through integrations (e.g., Slack, Intercom). Each comment belongs to exactly one parent entity.
type CommentFields struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The comment content in markdown format. This is a derived representation of the canonical bodyData ProseMirror content.
	Body string `json:"body"`
	// Comment's URL.
	Url string `json:"url"`
	// The time at which the entity was created.
	CreatedAt time.Time `json:"createdAt"`
	// The time the comment was last edited by its author. Null if the comment has not been edited since creation.
	EditedAt time.Time `json:"editedAt"`
	// The ID of the parent comment under which the current comment is nested. Null for top-level comments.
	ParentId string `json:"parentId"`
	// The user who wrote the comment. Null for comments created by integrations or bots without a user association.
	User *CommentFieldsUser `json:"user"`
	// The bot that created the comment.
	BotActor *CommentFieldsBotActorActorBot `json:"botActor"`
	// The external user who wrote the comment, when the comment was created through an integration such as Slack or Intercom. Null for comments created by workspace users.
	ExternalUser *CommentFieldsExternalUser `json:"externalUser"`
}

// GetId returns CommentFields.Id, and is useful for accessing the field via an interface.
func (v *CommentFields) GetId() string { return v.Id }

// GetBody returns CommentFields.Body, and is useful for accessing the field via an interface.
func (v *CommentFields) GetBody() string { return v.Body }

// GetUrl returns CommentFields.Url, and is useful for accessing the field via an interface.
func (v *CommentFields) GetUrl() string { return v.Url }

// GetCreatedAt returns CommentFields.CreatedAt, and is useful for accessing the field via an interface.
func (v *CommentFields) GetCreatedAt() time.Time { return v.CreatedAt }

// GetEditedAt returns CommentFields.EditedAt, and is useful for accessing the field via an interface.
func (v *CommentFields) GetEditedAt() time.Time { return v.EditedAt }

// GetParentId returns CommentFields.ParentId, and is useful for accessing the field via an interface.
func (v *CommentFields) GetParentId() string { return v.ParentId }

// GetUser returns CommentFields.User, and is useful for accessing the field via an interface.
func (v *CommentFields) GetUser() *CommentFieldsUser { return v.User }

// GetBotActor returns CommentFields.BotActor, and is useful for accessing the field via an interface.
func (v *CommentFields) GetBotActor() *CommentFieldsBotActorActorBot { return v.BotActor }

// GetExternalUser returns CommentFields.ExternalUser, and is useful for accessing the field via an interface.
func (v *CommentFields) GetExternalUser() *CommentFieldsExternalUser { return v.ExternalUser }

// CommentFieldsBotActorActorBot includes the requested fields of the GraphQL type ActorBot.
// The GraphQL type's documentation follows.
//
// A bot actor representing a non-human entity that performed an action, such as an integration (GitHub, Slack, Zendesk), an AI assistant, or an automated workflow. Bot actors are displayed in activity feeds and history to indicate when changes were made by applications rather than users.
type CommentFieldsBotActorActorBot struct {
	// The display name of the bot.
	Name string `json:"name"`
}

// GetName returns CommentFieldsBotActorActorBot.Name, and is useful for accessing the field via an interface.
func (v *CommentFieldsBotActorActorBot) GetName() string { return v.Name }

// CommentFieldsExternalUser includes the requested fields of the GraphQL type ExternalUser.
// The GraphQL type's documentation follows.
//
// An external user who interacts with Linear through an integrated external service (such as Slack, Jira, GitHub, GitLab, Salesforce, or Microsoft Teams) but does not have a Linear account. External users can create issues, post comments, and add reactions from their respective platforms. They are identified by service-specific user IDs and may optionally have an email address. External users are scoped to a single workspace.
type CommentFieldsExternalUser struct {
	// The external user's full name.
	Name string `json:"name"`
}

// GetName returns CommentFieldsExternalUser.Name, and is useful for accessing the field via an interface.
func (v *CommentFieldsExternalUser) GetName() string { return v.Name }

// CommentFieldsUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that belongs to a workspace. Users can have different roles (admin, member, guest, or app) that determine their level of access. Users can be members of multiple teams, and can be active or deactivated. Guest users have limited access scoped to specific teams they are invited to.
type CommentFieldsUser struct {
	// The user's display (nick) name. Must be unique within the workspace.
	DisplayName string `json:"displayName"`
}

// GetDisplayName returns CommentFieldsUser.DisplayName, and is useful for accessing the field via an interface.
func (v *CommentFieldsUser) GetDisplayName() string { return v.DisplayName }

// CreateCommentCommentCreateCommentPayload includes the requested fields of the GraphQL type CommentPayload.
// The GraphQL type's documentation follows.
//
// The result of a comment mutation.
type CreateCommentCommentCreateCommentPayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
	// The comment that was created or updated.
	Comment CreateCommentCommentCreateCommentPayloadComment `json:"comment"`
}

// GetSuccess returns CreateCommentCommentCreateCommentPayload.Success, and is useful for accessing the field via an interface.
func (v *CreateCommentCommentCreateCommentPayload) GetSuccess() bool { return v.Success }

// GetComment returns CreateCommentCommentCreateCommentPayload.Comment, and is useful for accessing the field via an interface.
func (v *CreateCommentCommentCreateCommentPayload) GetComment() CreateCommentCommentCreateCommentPayloadComment {
	return v.Comment
}

// CreateCommentCommentCreateCommentPayloadComment includes the requested fields of the GraphQL type Comment.
// The GraphQL type's documentation follows.
//
// A comment associated with an issue, project update, initiative update, document content, post, project, or initiative. Comments support rich text (ProseMirror), emoji reactions, and threaded replies via parentId. Comments can be created by workspace users or by external users through integrations (e.g., Slack, Intercom). Each comment belongs to exactly one parent entity.
type CreateCommentCommentCreateCommentPayloadComment struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Comment's URL.
	Url string `json:"url"`
}

// GetId returns CreateCommentCommentCreateCommentPayloadComment.Id, and is useful for accessing the field via an interface.
func (v *CreateCommentCommentCreateCommentPayloadComment) GetId() string { return v.Id }

// GetUrl returns CreateCommentCommentCreateCommentPayloadComment.Url, and is useful for accessing the field via an interface.
func (v *CreateCommentCommentCreateCommentPayloadComment) GetUrl() string { return v.Url }

// CreateCommentResponse is returned by CreateComment on success.
type CreateCommentResponse struct {
	// Creates a new comment.
	CommentCreate CreateCommentCommentCreateCommentPayload `json:"commentCreate"`
}

// GetCommentCreate returns CreateCommentResponse.CommentCreate, and is useful for accessing the field via an interface.
func (v *CreateCommentResponse) GetCommentCreate() CreateCommentCommentCreateCommentPayload {
	return v.CommentCreate
}

// FileUploadFileUploadUploadPayload includes the requested fields of the GraphQL type UploadPayload.
type FileUploadFileUploadUploadPayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
	// The upload file details including signed URL, asset URL, and required headers. Null if the upload could not be prepared.
	UploadFile *FileUploadFileUploadUploadPayloadUploadFile `json:"uploadFile"`
}

// GetSuccess returns FileUploadFileUploadUploadPayload.Success, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayload) GetSuccess() bool { return v.Success }

// GetUploadFile returns FileUploadFileUploadUploadPayload.UploadFile, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayload) GetUploadFile() *FileUploadFileUploadUploadPayloadUploadFile {
	return v.UploadFile
}

// FileUploadFileUploadUploadPayloadUploadFile includes the requested fields of the GraphQL type UploadFile.
// The GraphQL type's documentation follows.
//
// Represents a file upload destination with a pre-signed upload URL, asset URL, and required request headers for uploading to cloud storage.
type FileUploadFileUploadUploadPayloadUploadFile struct {
	// The pre-signed URL to which the file should be uploaded via a PUT request.
	UploadUrl string `json:"uploadUrl"`
	// The permanent asset URL where the file will be accessible after upload.
	AssetUrl string `json:"assetUrl"`
	// HTTP headers that must be included in the PUT request to the upload URL.
	Headers []FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader `json:"headers"`
}

// GetUploadUrl returns FileUploadFileUploadUploadPayloadUploadFile.UploadUrl, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayloadUploadFile) GetUploadUrl() string { return v.UploadUrl }

// GetAssetUrl returns FileUploadFileUploadUploadPayloadUploadFile.AssetUrl, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayloadUploadFile) GetAssetUrl() string { return v.AssetUrl }

// GetHeaders returns FileUploadFileUploadUploadPayloadUploadFile.Headers, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayloadUploadFile) GetHeaders() []FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader {
	return v.Headers
}

// FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader includes the requested fields of the GraphQL type UploadFileHeader.
type FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader struct {
	// Upload file header key.
	Key string `json:"key"`
	// Upload file header value.
	Value string `json:"value"`
}

// GetKey returns FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader.Key, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader) GetKey() string {
	return v.Key
}

// GetValue returns FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader.Value, and is useful for accessing the field via an interface.
func (v *FileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader) GetValue() string {
	return v.Value
}

// FileUploadResponse is returned by FileUpload on success.
type FileUploadResponse struct {
	// XHR request payload to upload an images, video and other attachments directly to Linear's cloud storage.
	FileUpload FileUploadFileUploadUploadPayload `json:"fileUpload"`
}

// GetFileUpload returns FileUploadResponse.FileUpload, and is useful for accessing the field via an interface.
func (v *FileUploadResponse) GetFileUpload() FileUploadFileUploadUploadPayload { return v.FileUpload }

// IssueCommentsIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type IssueCommentsIssue struct {
	// Comments associated with the issue, including inline comments on the issue's description.
	Comments IssueCommentsIssueCommentsCommentConnection `json:"comments"`
}

// GetComments returns IssueCommentsIssue.Comments, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssue) GetComments() IssueCommentsIssueCommentsCommentConnection {
	return v.Comments
}

// IssueCommentsIssueCommentsCommentConnection includes the requested fields of the GraphQL type CommentConnection.
type IssueCommentsIssueCommentsCommentConnection struct {
	Nodes    []IssueCommentsIssueCommentsCommentConnectionNodesComment `json:"nodes"`
	PageInfo IssueCommentsIssueCommentsCommentConnectionPageInfo       `json:"pageInfo"`
}

// GetNodes returns IssueCommentsIssueCommentsCommentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnection) GetNodes() []IssueCommentsIssueCommentsCommentConnectionNodesComment {
	return v.Nodes
}

// GetPageInfo returns IssueCommentsIssueCommentsCommentConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnection) GetPageInfo() IssueCommentsIssueCommentsCommentConnectionPageInfo {
	return v.PageInfo
}

// IssueCommentsIssueCommentsCommentConnectionNodesComment includes the requested fields of the GraphQL type Comment.
// The GraphQL type's documentation follows.
//
// A comment associated with an issue, project update, initiative update, document content, post, project, or initiative. Comments support rich text (ProseMirror), emoji reactions, and threaded replies via parentId. Comments can be created by workspace users or by external users through integrations (e.g., Slack, Intercom). Each comment belongs to exactly one parent entity.
type IssueCommentsIssueCommentsCommentConnectionNodesComment struct {
	CommentFields `json:"-"`
}

// GetId returns IssueCommentsIssueCommentsCommentConnectionNodesComment.Id, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetId() string {
	return v.CommentFields.Id
}

// GetBody returns IssueCommentsIssueCommentsCommentConnectionNodesComment.Body, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetBody() string {
	return v.CommentFields.Body
}

// GetUrl returns IssueCommentsIssueCommentsCommentConnectionNodesComment.Url, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetUrl() string {
	return v.CommentFields.Url
}

// GetCreatedAt returns IssueCommentsIssueCommentsCommentConnectionNodesComment.CreatedAt, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetCreatedAt() time.Time {
	return v.CommentFields.CreatedAt
}

// GetEditedAt returns IssueCommentsIssueCommentsCommentConnectionNodesComment.EditedAt, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetEditedAt() time.Time {
	return v.CommentFields.EditedAt
}

// GetParentId returns IssueCommentsIssueCommentsCommentConnectionNodesComment.ParentId, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetParentId() string {
	return v.CommentFields.ParentId
}

// GetUser returns IssueCommentsIssueCommentsCommentConnectionNodesComment.User, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetUser() *CommentFieldsUser {
	return v.CommentFields.User
}

// GetBotActor returns IssueCommentsIssueCommentsCommentConnectionNodesComment.BotActor, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetBotActor() *CommentFieldsBotActorActorBot {
	return v.CommentFields.BotActor
}

// GetExternalUser returns IssueCommentsIssueCommentsCommentConnectionNodesComment.ExternalUser, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) GetExternalUser() *CommentFieldsExternalUser {
	return v.CommentFields.ExternalUser
}

func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*IssueCommentsIssueCommentsCommentConnectionNodesComment
		graphql.NoUnmarshalJSON
	}
	firstPass.IssueCommentsIssueCommentsCommentConnectionNodesComment = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.CommentFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalIssueCommentsIssueCommentsCommentConnectionNodesComment struct {
	Id string `json:"id"`

	Body string `json:"body"`

	Url string `json:"url"`

	CreatedAt time.Time `json:"createdAt"`

	EditedAt time.Time `json:"editedAt"`

	ParentId string `json:"parentId"`

	User *CommentFieldsUser `json:"user"`

	BotActor *CommentFieldsBotActorActorBot `json:"botActor"`

	ExternalUser *CommentFieldsExternalUser `json:"externalUser"`
}

func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *IssueCommentsIssueCommentsCommentConnectionNodesComment) __premarshalJSON() (*__premarshalIssueCommentsIssueCommentsCommentConnectionNodesComment, error) {
	var retval __premarshalIssueCommentsIssueCommentsCommentConnectionNodesComment

	retval.Id = v.CommentFields.Id
	retval.Body = v.CommentFields.Body
	retval.Url = v.CommentFields.Url
	retval.CreatedAt = v.CommentFields.CreatedAt
	retval.EditedAt = v.CommentFields.EditedAt
	retval.ParentId = v.CommentFields.ParentId
	retval.User = v.CommentFields.User
	retval.BotActor = v.CommentFields.BotActor
	retval.ExternalUser = v.CommentFields.ExternalUser
	return &retval, nil
}

// IssueCommentsIssueCommentsCommentConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type IssueCommentsIssueCommentsCommentConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns IssueCommentsIssueCommentsCommentConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns IssueCommentsIssueCommentsCommentConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *IssueCommentsIssueCommentsCommentConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// IssueCommentsResponse is returned by IssueComments on success.
type IssueCommentsResponse struct {
	// One specific issue, looked up by its unique identifier.
	Issue IssueCommentsIssue `json:"issue"`
}

// GetIssue returns IssueCommentsResponse.Issue, and is useful for accessing the field via an interface.
func (v *IssueCommentsResponse) GetIssue() IssueCommentsIssue { return v.Issue }

// IssueDetailsIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type IssueDetailsIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title. This is the primary human-readable summary of the work item.
	Title string `json:"title"`
	// Issue URL.
	Url string `json:"url"`
	// The issue's description in markdown format.
	Description string `json:"description"`
	// Label for the priority.
	PriorityLabel string `json:"priorityLabel"`
	// The time at which the entity was created.
	CreatedAt time.Time `json:"createdAt"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt time.Time `json:"updatedAt"`
	// The workflow state (issue status) that the issue is currently in. Workflow states represent the issue's progress through the team's workflow, such as Triage, Todo, In Progress, Done, or Canceled.
	State IssueDetailsIssueStateWorkflowState `json:"state"`
	// The team that the issue belongs to. Every issue must belong to exactly one team, which determines the available workflow states, labels, and other team-specific configuration.
	Team IssueDetailsIssueTeam `json:"team"`
	// The user to whom the issue is assigned. Null if the issue is unassigned.
	Assignee *IssueDetailsIssueAssigneeUser `json:"assignee"`
	// The user who created the issue. Null if the creator's account has been deleted or if the issue was created by an integration or system process.
	Creator *IssueDetailsIssueCreatorUser `json:"creator"`
	// Labels associated with this issue.
	Labels IssueDetailsIssueLabelsIssueLabelConnection `json:"labels"`
	// Attachments associated with the issue.
	Attachments IssueDetailsIssueAttachmentsAttachmentConnection `json:"attachments"`
}

// GetId returns IssueDetailsIssue.Id, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetId() string { return v.Id }

// GetIdentifier returns IssueDetailsIssue.Identifier, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns IssueDetailsIssue.Title, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetTitle() string { return v.Title }

// GetUrl returns IssueDetailsIssue.Url, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetUrl() string { return v.Url }

// GetDescription returns IssueDetailsIssue.Description, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetDescription() string { return v.Description }

// GetPriorityLabel returns IssueDetailsIssue.PriorityLabel, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetPriorityLabel() string { return v.PriorityLabel }

// GetCreatedAt returns IssueDetailsIssue.CreatedAt, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns IssueDetailsIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetState returns IssueDetailsIssue.State, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetState() IssueDetailsIssueStateWorkflowState { return v.State }

// GetTeam returns IssueDetailsIssue.Team, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetTeam() IssueDetailsIssueTeam { return v.Team }

// GetAssignee returns IssueDetailsIssue.Assignee, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetAssignee() *IssueDetailsIssueAssigneeUser { return v.Assignee }

// GetCreator returns IssueDetailsIssue.Creator, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetCreator() *IssueDetailsIssueCreatorUser { return v.Creator }

// GetLabels returns IssueDetailsIssue.Labels, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetLabels() IssueDetailsIssueLabelsIssueLabelConnection { return v.Labels }

// GetAttachments returns IssueDetailsIssue.Attachments, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssue) GetAttachments() IssueDetailsIssueAttachmentsAttachmentConnection {
	return v.Attachments
}

// IssueDetailsIssueAssigneeUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that belongs to a workspace. Users can have different roles (admin, member, guest, or app) that determine their level of access. Users can be members of multiple teams, and can be active or deactivated. Guest users have limited access scoped to specific teams they are invited to.
type IssueDetailsIssueAssigneeUser struct {
	// The user's display (nick) name. Must be unique within the workspace.
	DisplayName string `json:"displayName"`
}

// GetDisplayName returns IssueDetailsIssueAssigneeUser.DisplayName, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAssigneeUser) GetDisplayName() string { return v.DisplayName }

// IssueDetailsIssueAttachmentsAttachmentConnection includes the requested fields of the GraphQL type AttachmentConnection.
type IssueDetailsIssueAttachmentsAttachmentConnection struct {
	Nodes []IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment `json:"nodes"`
}

// GetNodes returns IssueDetailsIssueAttachmentsAttachmentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAttachmentsAttachmentConnection) GetNodes() []IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment {
	return v.Nodes
}

// IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment includes the requested fields of the GraphQL type Attachment.
// The GraphQL type's documentation follows.
//
// An attachment linking external content to an issue. Attachments represent connections to external resources such as GitHub pull requests, Slack messages, Zendesk tickets, Figma files, Sentry issues, Intercom conversations, and plain URLs. Each attachment has a title and subtitle displayed in the Linear UI, a URL serving as both the link destination and unique identifier per issue, and optional metadata specific to the source integration.
type IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Content for the title line in the Linear attachment widget.
	Title string `json:"title"`
	// Content for the subtitle line in the Linear attachment widget.
	Subtitle string `json:"subtitle"`
	// The URL of the external resource this attachment links to. Also serves as a unique identifier for the attachment within an issue; no two attachments on the same issue can share the same URL.
	Url string `json:"url"`
	// The source type of the attachment, derived from the source metadata. Returns the integration type (e.g., 'github', 'slack', 'zendesk') or 'unknown' if no source is set.
	SourceType string `json:"sourceType"`
}

// GetId returns IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Id, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetId() string { return v.Id }

// GetTitle returns IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Title, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetTitle() string {
	return v.Title
}

// GetSubtitle returns IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Subtitle, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetSubtitle() string {
	return v.Subtitle
}

// GetUrl returns IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Url, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetUrl() string {
	return v.Url
}

// GetSourceType returns IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.SourceType, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetSourceType() string {
	return v.SourceType
}

// IssueDetailsIssueCreatorUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that belongs to a workspace. Users can have different roles (admin, member, guest, or app) that determine their level of access. Users can be members of multiple teams, and can be active or deactivated. Guest users have limited access scoped to specific teams they are invited to.
type IssueDetailsIssueCreatorUser struct {
	// The user's display (nick) name. Must be unique within the workspace.
	DisplayName string `json:"displayName"`
}

// GetDisplayName returns IssueDetailsIssueCreatorUser.DisplayName, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueCreatorUser) GetDisplayName() string { return v.DisplayName }

// IssueDetailsIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type IssueDetailsIssueLabelsIssueLabelConnection struct {
	Nodes []IssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns IssueDetailsIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueLabelsIssueLabelConnection) GetNodes() []IssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// IssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues. Labels help categorize and filter issues across a workspace. They can be workspace-level (shared across all teams) or team-scoped. Labels have a color for visual identification and can be organized hierarchically into groups, where a parent label acts as a group containing child labels. Labels may also be inherited from parent teams to sub-teams.
type IssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns IssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string { return v.Name }

// IssueDetailsIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team's workflow, representing an issue status such as Triage, Backlog, Todo, In Progress, In Review, Done, or Canceled. Each team has its own set of workflow states that define the progression of issues through the team's process. Workflow states have a type that categorizes them (triage, backlog, unstarted, started, completed, canceled), a position that determines their display order, and a color for visual identification. States can be inherited from parent teams to sub-teams.
type IssueDetailsIssueStateWorkflowState struct {
	// The state's human-readable name (e.g., 'In Progress', 'Done', 'Backlog').
	Name string `json:"name"`
}

// GetName returns IssueDetailsIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueStateWorkflowState) GetName() string { return v.Name }

// IssueDetailsIssueTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type IssueDetailsIssueTeam struct {
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
}

// GetKey returns IssueDetailsIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *IssueDetailsIssueTeam) GetKey() string { return v.Key }

// IssueDetailsResponse is returned by IssueDetails on success.
type IssueDetailsResponse struct {
	// One specific issue, looked up by its unique identifier.
	Issue IssueDetailsIssue `json:"issue"`
}

// GetIssue returns IssueDetailsResponse.Issue, and is useful for accessing the field via an interface.
func (v *IssueDetailsResponse) GetIssue() IssueDetailsIssue { return v.Issue }

// UpdateCommentCommentUpdateCommentPayload includes the requested fields of the GraphQL type CommentPayload.
// The GraphQL type's documentation follows.
//
// The result of a comment mutation.
type UpdateCommentCommentUpdateCommentPayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
	// The comment that was created or updated.
	Comment UpdateCommentCommentUpdateCommentPayloadComment `json:"comment"`
}

// GetSuccess returns UpdateCommentCommentUpdateCommentPayload.Success, and is useful for accessing the field via an interface.
func (v *UpdateCommentCommentUpdateCommentPayload) GetSuccess() bool { return v.Success }

// GetComment returns UpdateCommentCommentUpdateCommentPayload.Comment, and is useful for accessing the field via an interface.
func (v *UpdateCommentCommentUpdateCommentPayload) GetComment() UpdateCommentCommentUpdateCommentPayloadComment {
	return v.Comment
}

// UpdateCommentCommentUpdateCommentPayloadComment includes the requested fields of the GraphQL type Comment.
// The GraphQL type's documentation follows.
//
// A comment associated with an issue, project update, initiative update, document content, post, project, or initiative. Comments support rich text (ProseMirror), emoji reactions, and threaded replies via parentId. Comments can be created by workspace users or by external users through integrations (e.g., Slack, Intercom). Each comment belongs to exactly one parent entity.
type UpdateCommentCommentUpdateCommentPayloadComment struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Comment's URL.
	Url string `json:"url"`
}

// GetId returns UpdateCommentCommentUpdateCommentPayloadComment.Id, and is useful for accessing the field via an interface.
func (v *UpdateCommentCommentUpdateCommentPayloadComment) GetId() string { return v.Id }

// GetUrl returns UpdateCommentCommentUpdateCommentPayloadComment.Url, and is useful for accessing the field via an interface.
func (v *UpdateCommentCommentUpdateCommentPayloadComment) GetUrl() string { return v.Url }

// UpdateCommentResponse is returned by UpdateComment on success.
type UpdateCommentResponse struct {
	// Updates a comment.
	CommentUpdate UpdateCommentCommentUpdateCommentPayload `json:"commentUpdate"`
}

// GetCommentUpdate returns UpdateCommentResponse.CommentUpdate, and is useful for accessing the field via an interface.
func (v *UpdateCommentResponse) GetCommentUpdate() UpdateCommentCommentUpdateCommentPayload {
	return v.CommentUpdate
}

// ViewerOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// A workspace (referred to as Organization in the API). Workspaces are the root-level container for all teams, users, projects, issues, and settings. Every user belongs to at least one workspace, and all data is scoped within a workspace boundary.
type ViewerOrganization struct {
	// The workspace's name.
	Name string `json:"name"`
	// The workspace's unique URL key, used in URLs to identify the workspace.
	UrlKey string `json:"urlKey"`
}

// GetName returns ViewerOrganization.Name, and is useful for accessing the field via an interface.
func (v *ViewerOrganization) GetName() string { return v.Name }

// GetUrlKey returns ViewerOrganization.UrlKey, and is useful for accessing the field via an interface.
func (v *ViewerOrganization) GetUrlKey() string { return v.UrlKey }

// ViewerResponse is returned by Viewer on success.
type ViewerResponse struct {
	// The currently authenticated user making the API request.
	Viewer ViewerViewerUser `json:"viewer"`
	// The authenticated user's workspace.
	Organization ViewerOrganization `json:"organization"`
	// All teams whose issues the user can access. This includes public teams and private teams the user is a member of. This may differ from `administrableTeams`, which returns teams whose settings the user can change but whose issues they don't necessarily have access to.
	Teams ViewerTeamsTeamConnection `json:"teams"`
}

// GetViewer returns ViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetViewer() ViewerViewerUser { return v.Viewer }

// GetOrganization returns ViewerResponse.Organization, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetOrganization() ViewerOrganization { return v.Organization }

// GetTeams returns ViewerResponse.Teams, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetTeams() ViewerTeamsTeamConnection { return v.Teams }

// ViewerTeamsTeamConnection includes the requested fields of the GraphQL type TeamConnection.
type ViewerTeamsTeamConnection struct {
	Nodes []ViewerTeamsTeamConnectionNodesTeam `json:"nodes"`
}

// GetNodes returns ViewerTeamsTeamConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ViewerTeamsTeamConnection) GetNodes() []ViewerTeamsTeamConnectionNodesTeam { return v.Nodes }

// ViewerTeamsTeamConnectionNodesTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type ViewerTeamsTeamConnectionNodesTeam struct {
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
	// The team's name.
	Name string `json:"name"`
}

// GetKey returns ViewerTeamsTeamConnectionNodesTeam.Key, and is useful for accessing the field via an interface.
func (v *ViewerTeamsTeamConnectionNodesTeam) GetKey() string { return v.Key }

// GetName returns ViewerTeamsTeamConnectionNodesTeam.Name, and is useful for accessing the field via an interface.
func (v *ViewerTeamsTeamConnectionNodesTeam) GetName() string { return v.Name }

// ViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that belongs to a workspace. Users can have different roles (admin, member, guest, or app) that determine their level of access. Users can be members of multiple teams, and can be active or deactivated. Guest users have limited access scoped to specific teams they are invited to.
type ViewerViewerUser struct {
	// The user's full name.
	Name string `json:"name"`
	// The user's email address.
	Email string `json:"email"`
}

// GetName returns ViewerViewerUser.Name, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetName() string { return v.Name }

// GetEmail returns ViewerViewerUser.Email, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetEmail() string { return v.Email }

// __CommentByIDInput is used internally by genqlient
type __CommentByIDInput struct {
	Id string `json:"id"`
}

// GetId returns __CommentByIDInput.Id, and is useful for accessing the field via an interface.
func (v *__CommentByIDInput) GetId() string { return v.Id }

// __CreateCommentInput is used internally by genqlient
type __CreateCommentInput struct {
	IssueId  string  `json:"issueId"`
	Body     string  `json:"body"`
	ParentId *string `json:"parentId"`
}

// GetIssueId returns __CreateCommentInput.IssueId, and is useful for accessing the field via an interface.
func (v *__CreateCommentInput) GetIssueId() string { return v.IssueId }

// GetBody returns __CreateCommentInput.Body, and is useful for accessing the field via an interface.
func (v *__CreateCommentInput) GetBody() string { return v.Body }

// GetParentId returns __CreateCommentInput.ParentId, and is useful for accessing the field via an interface.
func (v *__CreateCommentInput) GetParentId() *string { return v.ParentId }

// __FileUploadInput is used internally by genqlient
type __FileUploadInput struct {
	ContentType string `json:"contentType"`
	Filename    string `json:"filename"`
	Size        int    `json:"size"`
}

// GetContentType returns __FileUploadInput.ContentType, and is useful for accessing the field via an interface.
func (v *__FileUploadInput) GetContentType() string { return v.ContentType }

// GetFilename returns __FileUploadInput.Filename, and is useful for accessing the field via an interface.
func (v *__FileUploadInput) GetFilename() string { return v.Filename }

// GetSize returns __FileUploadInput.Size, and is useful for accessing the field via an interface.
func (v *__FileUploadInput) GetSize() int { return v.Size }

// __IssueCommentsInput is used internally by genqlient
type __IssueCommentsInput struct {
	Id    string  `json:"id"`
	After *string `json:"after"`
}

// GetId returns __IssueCommentsInput.Id, and is useful for accessing the field via an interface.
func (v *__IssueCommentsInput) GetId() string { return v.Id }

// GetAfter returns __IssueCommentsInput.After, and is useful for accessing the field via an interface.
func (v *__IssueCommentsInput) GetAfter() *string { return v.After }

// __IssueDetailsInput is used internally by genqlient
type __IssueDetailsInput struct {
	Id string `json:"id"`
}

// GetId returns __IssueDetailsInput.Id, and is useful for accessing the field via an interface.
func (v *__IssueDetailsInput) GetId() string { return v.Id }

// __UpdateCommentInput is used internally by genqlient
type __UpdateCommentInput struct {
	Id   string `json:"id"`
	Body string `json:"body"`
}

// GetId returns __UpdateCommentInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateCommentInput) GetId() string { return v.Id }

// GetBody returns __UpdateCommentInput.Body, and is useful for accessing the field via an interface.
func (v *__UpdateCommentInput) GetBody() string { return v.Body }

// The query executed by CommentByID.
const CommentByID_Operation = `
query CommentByID ($id: String!) {
	comment(id: $id) {
		id
		body
		issue {
			identifier
		}
	}
}
`

func CommentByID(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *CommentByIDResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CommentByID",
		Query:  CommentByID_Operation,
		Variables: &__CommentByIDInput{
			Id: id,
		},
	}

	data_ = &CommentByIDResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateComment.
const CreateComment_Operation = `
mutation CreateComment ($issueId: String!, $body: String!, $parentId: String) {
	commentCreate(input: {issueId:$issueId,body:$body,parentId:$parentId}) {
		success
		comment {
			id
			url
		}
	}
}
`

func CreateComment(
	ctx_ context.Context,
	client_ graphql.Client,
	issueId string,
	body string,
	parentId *string,
) (data_ *CreateCommentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateComment",
		Query:  CreateComment_Operation,
		Variables: &__CreateCommentInput{
			IssueId:  issueId,
			Body:     body,
			ParentId: parentId,
		},
	}

	data_ = &CreateCommentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by FileUpload.
const FileUpload_Operation = `
mutation FileUpload ($contentType: String!, $filename: String!, $size: Int!) {
	fileUpload(contentType: $contentType, filename: $filename, size: $size) {
		success
		uploadFile {
			uploadUrl
			assetUrl
			headers {
				key
				value
			}
		}
	}
}
`

func FileUpload(
	ctx_ context.Context,
	client_ graphql.Client,
	contentType string,
	filename string,
	size int,
) (data_ *FileUploadResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "FileUpload",
		Query:  FileUpload_Operation,
		Variables: &__FileUploadInput{
			ContentType: contentType,
			Filename:    filename,
			Size:        size,
		},
	}

	data_ = &FileUploadResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by IssueComments.
const IssueComments_Operation = `
query IssueComments ($id: String!, $after: String) {
	issue(id: $id) {
		comments(first: 100, after: $after) {
			nodes {
				... CommentFields
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
fragment CommentFields on Comment {
	id
	body
	url
	createdAt
	editedAt
	parentId
	user {
		displayName
	}
	botActor {
		name
	}
	externalUser {
		name
	}
}
`

func IssueComments(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
	after *string,
) (data_ *IssueCommentsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "IssueComments",
		Query:  IssueComments_Operation,
		Variables: &__IssueCommentsInput{
			Id:    id,
			After: after,
		},
	}

	data_ = &IssueCommentsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by IssueDetails.
const IssueDetails_Operation = `
query IssueDetails ($id: String!) {
	issue(id: $id) {
		id
		identifier
		title
		url
		description
		priorityLabel
		createdAt
		updatedAt
		state {
			name
		}
		team {
			key
		}
		assignee {
			displayName
		}
		creator {
			displayName
		}
		labels(first: 100) {
			nodes {
				name
			}
		}
		attachments(first: 100) {
			nodes {
				id
				title
				subtitle
				url
				sourceType
			}
		}
	}
}
`

func IssueDetails(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *IssueDetailsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "IssueDetails",
		Query:  IssueDetails_Operation,
		Variables: &__IssueDetailsInput{
			Id: id,
		},
	}

	data_ = &IssueDetailsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdateComment.
const UpdateComment_Operation = `
mutation UpdateComment ($id: String!, $body: String!) {
	commentUpdate(id: $id, input: {body:$body}) {
		success
		comment {
			id
			url
		}
	}
}
`

func UpdateComment(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
	body string,
) (data_ *UpdateCommentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateComment",
		Query:  UpdateComment_Operation,
		Variables: &__UpdateCommentInput{
			Id:   id,
			Body: body,
		},
	}

	data_ = &UpdateCommentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Viewer.
const Viewer_Operation = `
query Viewer {
	viewer {
		name
		email
	}
	organization {
		name
		urlKey
	}
	teams(first: 250) {
		nodes {
			key
			name
		}
	}
}
`

func Viewer(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ViewerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Viewer",
		Query:  Viewer_Operation,
	}

	data_ = &ViewerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
