query Viewer {
  viewer {
    name
    email
  }
  organization {
    name
    urlKey
  }
  teams(first: 250) {
    nodes {
      key
      name
    }
  }
}

query IssueDetails($id: String!) {
  issue(id: $id) {
    id
    identifier
    title
    url
    description
    priorityLabel
    createdAt
    updatedAt
    state {
      name
    }
    team {
      key
    }
    # @genqlient(pointer: true)
    assignee {
      displayName
    }
    # @genqlient(pointer: true)
    creator {
      displayName
    }
    labels(first: 100) {
      nodes {
        name
      }
    }
    attachments(first: 100) {
      nodes {
        id
        title
        subtitle
        url
        sourceType
      }
    }
  }
}

query IssueRef($id: String!) {
  issue(id: $id) {
    id
    identifier
    url
  }
}

query IssueComments(
  $id: String!
  # @genqlient(pointer: true)
  $after: String
) {
  issue(id: $id) {
    comments(first: 100, after: $after) {
      nodes {
        ...CommentFields
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

fragment CommentFields on Comment {
  id
  body
  url
  createdAt
  editedAt
  parentId
  # @genqlient(pointer: true)
  user {
    displayName
  }
  # @genqlient(pointer: true)
  botActor {
    name
  }
  # @genqlient(pointer: true)
  externalUser {
    name
  }
}

query CommentByID($id: String!) {
  comment(id: $id) {
    id
    body
    # @genqlient(pointer: true)
    issue {
      identifier
    }
  }
}

mutation CreateComment(
  $issueId: String!
  $body: String!
  # @genqlient(pointer: true)
  $parentId: String
) {
  commentCreate(input: { issueId: $issueId, body: $body, parentId: $parentId }) {
    success
    comment {
      id
      url
    }
  }
}

mutation UpdateComment($id: String!, $body: String!) {
  commentUpdate(id: $id, input: { body: $body }) {
    success
    comment {
      id
      url
    }
  }
}

mutation FileUpload($contentType: String!, $filename: String!, $size: Int!) {
  fileUpload(contentType: $contentType, filename: $filename, size: $size) {
    success
    # @genqlient(pointer: true)
    uploadFile {
      uploadUrl
      assetUrl
      headers {
        key
        value
      }
    }
  }
}
